### ISSUE TITLE
Words needed to be explained in glossary before turn in of project plan

### ISSUE THREAD

**Issue by Portals** [DATX02-20-02/Report#31]
- [ ] Road Agent - A bot that roads around in the world
- [ ] Mesh
- [ ] Main road, better explanation
- [ ] Streets, better explanation
